name: Bug Report
description: Report a bug
title: "[Bug]: <Describe a bug shortly>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please full a form and describe bug!
  - type: checkboxes
    label: Traits of bug
    id: typek
    attributes:
      description: Choose traits that describes this issue
      options:
        - label: Arithmetic error
  - type: textarea
    label: Please, describe!
  - type: textarea
    label: StackTrace
