name: Bug Report
description: Report a bug
title: "[Bug]: <Describe a bug shortly>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please full a form and describe bug!
  - type: textarea
    attributes:
      label: Describe a bug
      placeholder: Sometimes X return non-valid value
    validations:
      required: true
