[package]
name = "gen"
version = "1.0.0"
edition = "2021"

[dependencies]
tera = { version = "1", default-features = false }
anyhow = { version = "1" }
git2 = { version = "0.17.2", default-features = false }
clap = { version = "3", default-features = false, features = ["cargo", "std"] }

#globset = { version = "0.4", default-features = false }
#rustfmt-wrapper = { version = "0.2" }
#serde = { version = "1.0", default-features = false, features = ["std"] }
#serde_json = { version = "1.0", default-features = false, features = ["std"] }